image: Visual Studio 2017

version: 1.0.{build}

branches:
    only:
        - master

environment:
    COMPILER: msvc
    VSVER: 14.1

    matrix:
        - QT: C:\Qt\5.13\msvc2017_64
          PLATFORM: amd64
          MKSPEC: win64-msvc
        - QT: C:\Qt\5.13\msvc2017
          PLATFORM: x86
          MKSPEC: win32-msvc

clone_depth: 1

# scripts that run after cloning repository
install:
    - set PATH=%QT%\bin\;C:\Qt\Tools\QtCreator\bin\;%PATH%
    - set BOOST_ROOT=C:\Libraries\boost_1_69_0
    - git submodule update --init --recursive

# scripts that run before build
before_build:
    - cd 3rdparty\scintilla\qt\ScintillaEdit
    - python WidgetGen.py
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - if "%MKSPEC%" EQU "win64-msvc" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat")
    - if "%MKSPEC%" EQU "win32-msvc" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat")
    - qmake --version
    - mkdir build
    - cd build
    - if "%MKSPEC%" EQU "win64-msvc" (qmake -r -spec win32-msvc CONFIG+=x86_64 CONFIG+=qtquickcompiler CONFIG-=debug CONFIG+=release ../cjlv.pro)
    - if "%MKSPEC%" EQU "win32-msvc" (qmake -r -spec win32-msvc CONFIG+=Win32 CONFIG+=qtquickcompiler CONFIG-=debug CONFIG+=release ../cjlv.pro)

# custom build scripts
build_script:
    - jom -j 4

# scripts that run after build
after_build:
    - set cjlv_version=1.0
    - mkdir distrib\cjlv
    - windeployqt.exe --dir .\distrib\cjlv --qmldir "%APPVEYOR_BUILD_FOLDER%\qml" %APPVEYOR_BUILD_FOLDER%\build\release\cjlv.exe
    - copy "%APPVEYOR_BUILD_FOLDER%\build\release\cjlv.exe" "distrib\cjlv\cjlv.exe"
    - copy "%APPVEYOR_BUILD_FOLDER%\build\release\Everything*.dll" "distrib\cjlv\"
    - copy "%APPVEYOR_BUILD_FOLDER%\build\release\Everything.exe" "distrib\cjlv\"
    - echo %cjlv_version% > "distrib\cjlv\version.txt"
    - echo %APPVEYOR_REPO_COMMIT% >> "distrib\cjlv\version.txt"
    - copy "distrib\cjlv\cjlv.exe" "distrib\cjlv.exe"
    - cd distrib
    - 7z a cjlv_%MKSPEC%_full_%cjlv_version%.7z cjlv
    - 7z a cjlv_%MKSPEC%.7z cjlv.exe

artifacts:
    - path: build\distrib\cjlv_%MKSPEC%_full_%cjlv_version%.7z
      name: full_package
    - path: build\distrib\cjlv_%MKSPEC%.7z
      name: exe_only
